extern void glCullFace (GLenum mode);
extern void glFrontFace (GLenum mode);
extern void glHint (GLenum target, GLenum mode);
extern void glLineWidth (GLfloat width);
extern void glPointSize (GLfloat size);
extern void glPolygonMode (GLenum face, GLenum mode);
extern void glScissor (GLint x, GLint y, GLsizei width, GLsizei height);
extern void glTexParameterf (GLenum target, GLenum pname, GLfloat param);
extern void glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params);
extern void glTexParameteri (GLenum target, GLenum pname, GLint param);
extern void glTexParameteriv (GLenum target, GLenum pname, const GLint *params);
extern void glTexImage1D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels);
extern void glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
extern void glDrawBuffer (GLenum mode);
extern void glClear (GLbitfield mask);
extern void glClearColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void glClearStencil (GLint s);
extern void glClearDepth (GLdouble depth);
extern void glStencilMask (GLuint mask);
extern void glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void glDepthMask (GLboolean flag);
extern void glDisable (GLenum cap);
extern void glEnable (GLenum cap);
extern void glFinish (void);
extern void glFlush (void);
extern void glBlendFunc (GLenum sfactor, GLenum dfactor);
extern void glLogicOp (GLenum opcode);
extern void glStencilFunc (GLenum func, GLint ref, GLuint mask);
extern void glStencilOp (GLenum fail, GLenum zfail, GLenum zpass);
extern void glDepthFunc (GLenum func);
extern void glPixelStoref (GLenum pname, GLfloat param);
extern void glPixelStorei (GLenum pname, GLint param);
extern void glReadBuffer (GLenum mode);
extern void glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
extern void glGetBooleanv (GLenum pname, GLboolean *data);
extern void glGetDoublev (GLenum pname, GLdouble *data);
extern GLenum glGetError (void);
extern void glGetFloatv (GLenum pname, GLfloat *data);
extern void glGetIntegerv (GLenum pname, GLint *data);
extern const_GLubyte_* glGetString (GLenum name);
extern void glGetTexImage (GLenum target, GLint level, GLenum format, GLenum type, void *pixels);
extern void glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params);
extern void glGetTexParameteriv (GLenum target, GLenum pname, GLint *params);
extern void glGetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params);
extern void glGetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params);
extern GLboolean glIsEnabled (GLenum cap);
extern void glDepthRange (GLdouble near, GLdouble far);
extern void glViewport (GLint x, GLint y, GLsizei width, GLsizei height);
extern void glDrawArrays (GLenum mode, GLint first, GLsizei count);
extern void glDrawElements (GLenum mode, GLsizei count, GLenum type, const void *indices);
extern void glGetPointerv (GLenum pname, void **params);
extern void glPolygonOffset (GLfloat factor, GLfloat units);
extern void glCopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
extern void glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern void glCopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
extern void glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
extern void glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
extern void glBindTexture (GLenum target, GLuint texture);
extern void glDeleteTextures (GLsizei n, const GLuint *textures);
extern void glGenTextures (GLsizei n, GLuint *textures);
extern GLboolean glIsTexture (GLuint texture);
extern void glDrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
extern void glTexImage3D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
extern void glTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
extern void glCopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glActiveTexture (GLenum texture);
extern void glSampleCoverage (GLfloat value, GLboolean invert);
extern void glCompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data);
extern void glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
extern void glCompressedTexImage1D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data);
extern void glCompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
extern void glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
extern void glCompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
extern void glGetCompressedTexImage (GLenum target, GLint level, void *img);
extern void glBlendFuncSeparate (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
extern void glMultiDrawArrays (GLenum mode, const GLint *first, const GLsizei *count, GLsizei drawcount);
extern void glMultiDrawElements (GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount);
extern void glPointParameterf (GLenum pname, GLfloat param);
extern void glPointParameterfv (GLenum pname, const GLfloat *params);
extern void glPointParameteri (GLenum pname, GLint param);
extern void glPointParameteriv (GLenum pname, const GLint *params);
extern void glBlendColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void glBlendEquation (GLenum mode);
extern void glGenQueries (GLsizei n, GLuint *ids);
extern void glDeleteQueries (GLsizei n, const GLuint *ids);
extern GLboolean glIsQuery (GLuint id);
extern void glBeginQuery (GLenum target, GLuint id);
extern void glEndQuery (GLenum target);
extern void glGetQueryiv (GLenum target, GLenum pname, GLint *params);
extern void glGetQueryObjectiv (GLuint id, GLenum pname, GLint *params);
extern void glGetQueryObjectuiv (GLuint id, GLenum pname, GLuint *params);
extern void glBindBuffer (GLenum target, GLuint buffer);
extern void glDeleteBuffers (GLsizei n, const GLuint *buffers);
extern void glGenBuffers (GLsizei n, GLuint *buffers);
extern GLboolean glIsBuffer (GLuint buffer);
extern void glBufferData (GLenum target, GLsizeiptr size, const void *data, GLenum usage);
extern void glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
extern void glGetBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, void *data);
extern void* glMapBuffer (GLenum target, GLenum access);
extern GLboolean glUnmapBuffer (GLenum target);
extern void glGetBufferParameteriv (GLenum target, GLenum pname, GLint *params);
extern void glGetBufferPointerv (GLenum target, GLenum pname, void **params);
extern void glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha);
extern void glDrawBuffers (GLsizei n, const GLenum *bufs);
extern void glStencilOpSeparate (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
extern void glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask);
extern void glStencilMaskSeparate (GLenum face, GLuint mask);
extern void glAttachShader (GLuint program, GLuint shader);
extern void glBindAttribLocation (GLuint program, GLuint index, const GLchar *name);
extern void glCompileShader (GLuint shader);
extern GLuint glCreateProgram (void);
extern GLuint glCreateShader (GLenum type);
extern void glDeleteProgram (GLuint program);
extern void glDeleteShader (GLuint shader);
extern void glDetachShader (GLuint program, GLuint shader);
extern void glDisableVertexAttribArray (GLuint index);
extern void glEnableVertexAttribArray (GLuint index);
extern void glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
extern void glGetActiveUniform (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
extern void glGetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
extern GLint glGetAttribLocation (GLuint program, const GLchar *name);
extern void glGetProgramiv (GLuint program, GLenum pname, GLint *params);
extern void glGetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
extern void glGetShaderiv (GLuint shader, GLenum pname, GLint *params);
extern void glGetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
extern void glGetShaderSource (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
extern GLint glGetUniformLocation (GLuint program, const GLchar *name);
extern void glGetUniformfv (GLuint program, GLint location, GLfloat *params);
extern void glGetUniformiv (GLuint program, GLint location, GLint *params);
extern void glGetVertexAttribdv (GLuint index, GLenum pname, GLdouble *params);
extern void glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params);
extern void glGetVertexAttribiv (GLuint index, GLenum pname, GLint *params);
extern void glGetVertexAttribPointerv (GLuint index, GLenum pname, void **pointer);
extern GLboolean glIsProgram (GLuint program);
extern GLboolean glIsShader (GLuint shader);
extern void glLinkProgram (GLuint program);
extern void glShaderSource (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
extern void glUseProgram (GLuint program);
extern void glUniform1f (GLint location, GLfloat v0);
extern void glUniform2f (GLint location, GLfloat v0, GLfloat v1);
extern void glUniform3f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void glUniform4f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void glUniform1i (GLint location, GLint v0);
extern void glUniform2i (GLint location, GLint v0, GLint v1);
extern void glUniform3i (GLint location, GLint v0, GLint v1, GLint v2);
extern void glUniform4i (GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void glUniform1fv (GLint location, GLsizei count, const GLfloat *value);
extern void glUniform2fv (GLint location, GLsizei count, const GLfloat *value);
extern void glUniform3fv (GLint location, GLsizei count, const GLfloat *value);
extern void glUniform4fv (GLint location, GLsizei count, const GLfloat *value);
extern void glUniform1iv (GLint location, GLsizei count, const GLint *value);
extern void glUniform2iv (GLint location, GLsizei count, const GLint *value);
extern void glUniform3iv (GLint location, GLsizei count, const GLint *value);
extern void glUniform4iv (GLint location, GLsizei count, const GLint *value);
extern void glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glValidateProgram (GLuint program);
extern void glVertexAttrib1d (GLuint index, GLdouble x);
extern void glVertexAttrib1dv (GLuint index, const GLdouble *v);
extern void glVertexAttrib1f (GLuint index, GLfloat x);
extern void glVertexAttrib1fv (GLuint index, const GLfloat *v);
extern void glVertexAttrib1s (GLuint index, GLshort x);
extern void glVertexAttrib1sv (GLuint index, const GLshort *v);
extern void glVertexAttrib2d (GLuint index, GLdouble x, GLdouble y);
extern void glVertexAttrib2dv (GLuint index, const GLdouble *v);
extern void glVertexAttrib2f (GLuint index, GLfloat x, GLfloat y);
extern void glVertexAttrib2fv (GLuint index, const GLfloat *v);
extern void glVertexAttrib2s (GLuint index, GLshort x, GLshort y);
extern void glVertexAttrib2sv (GLuint index, const GLshort *v);
extern void glVertexAttrib3d (GLuint index, GLdouble x, GLdouble y, GLdouble z);
extern void glVertexAttrib3dv (GLuint index, const GLdouble *v);
extern void glVertexAttrib3f (GLuint index, GLfloat x, GLfloat y, GLfloat z);
extern void glVertexAttrib3fv (GLuint index, const GLfloat *v);
extern void glVertexAttrib3s (GLuint index, GLshort x, GLshort y, GLshort z);
extern void glVertexAttrib3sv (GLuint index, const GLshort *v);
extern void glVertexAttrib4Nbv (GLuint index, const GLbyte *v);
extern void glVertexAttrib4Niv (GLuint index, const GLint *v);
extern void glVertexAttrib4Nsv (GLuint index, const GLshort *v);
extern void glVertexAttrib4Nub (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
extern void glVertexAttrib4Nubv (GLuint index, const GLubyte *v);
extern void glVertexAttrib4Nuiv (GLuint index, const GLuint *v);
extern void glVertexAttrib4Nusv (GLuint index, const GLushort *v);
extern void glVertexAttrib4bv (GLuint index, const GLbyte *v);
extern void glVertexAttrib4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void glVertexAttrib4dv (GLuint index, const GLdouble *v);
extern void glVertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void glVertexAttrib4fv (GLuint index, const GLfloat *v);
extern void glVertexAttrib4iv (GLuint index, const GLint *v);
extern void glVertexAttrib4s (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
extern void glVertexAttrib4sv (GLuint index, const GLshort *v);
extern void glVertexAttrib4ubv (GLuint index, const GLubyte *v);
extern void glVertexAttrib4uiv (GLuint index, const GLuint *v);
extern void glVertexAttrib4usv (GLuint index, const GLushort *v);
extern void glVertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
extern void glUniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glUniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glUniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glUniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glUniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glUniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glColorMaski (GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
extern void glGetBooleani_v (GLenum target, GLuint index, GLboolean *data);
extern void glGetIntegeri_v (GLenum target, GLuint index, GLint *data);
extern void glEnablei (GLenum target, GLuint index);
extern void glDisablei (GLenum target, GLuint index);
extern GLboolean glIsEnabledi (GLenum target, GLuint index);
extern void glBeginTransformFeedback (GLenum primitiveMode);
extern void glEndTransformFeedback (void);
extern void glBindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern void glBindBufferBase (GLenum target, GLuint index, GLuint buffer);
extern void glTransformFeedbackVaryings (GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode);
extern void glGetTransformFeedbackVarying (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
extern void glClampColor (GLenum target, GLenum clamp);
extern void glBeginConditionalRender (GLuint id, GLenum mode);
extern void glEndConditionalRender (void);
extern void glVertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
extern void glGetVertexAttribIiv (GLuint index, GLenum pname, GLint *params);
extern void glGetVertexAttribIuiv (GLuint index, GLenum pname, GLuint *params);
extern void glVertexAttribI1i (GLuint index, GLint x);
extern void glVertexAttribI2i (GLuint index, GLint x, GLint y);
extern void glVertexAttribI3i (GLuint index, GLint x, GLint y, GLint z);
extern void glVertexAttribI4i (GLuint index, GLint x, GLint y, GLint z, GLint w);
extern void glVertexAttribI1ui (GLuint index, GLuint x);
extern void glVertexAttribI2ui (GLuint index, GLuint x, GLuint y);
extern void glVertexAttribI3ui (GLuint index, GLuint x, GLuint y, GLuint z);
extern void glVertexAttribI4ui (GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
extern void glVertexAttribI1iv (GLuint index, const GLint *v);
extern void glVertexAttribI2iv (GLuint index, const GLint *v);
extern void glVertexAttribI3iv (GLuint index, const GLint *v);
extern void glVertexAttribI4iv (GLuint index, const GLint *v);
extern void glVertexAttribI1uiv (GLuint index, const GLuint *v);
extern void glVertexAttribI2uiv (GLuint index, const GLuint *v);
extern void glVertexAttribI3uiv (GLuint index, const GLuint *v);
extern void glVertexAttribI4uiv (GLuint index, const GLuint *v);
extern void glVertexAttribI4bv (GLuint index, const GLbyte *v);
extern void glVertexAttribI4sv (GLuint index, const GLshort *v);
extern void glVertexAttribI4ubv (GLuint index, const GLubyte *v);
extern void glVertexAttribI4usv (GLuint index, const GLushort *v);
extern void glGetUniformuiv (GLuint program, GLint location, GLuint *params);
extern void glBindFragDataLocation (GLuint program, GLuint color, const GLchar *name);
extern GLint glGetFragDataLocation (GLuint program, const GLchar *name);
extern void glUniform1ui (GLint location, GLuint v0);
extern void glUniform2ui (GLint location, GLuint v0, GLuint v1);
extern void glUniform3ui (GLint location, GLuint v0, GLuint v1, GLuint v2);
extern void glUniform4ui (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern void glUniform1uiv (GLint location, GLsizei count, const GLuint *value);
extern void glUniform2uiv (GLint location, GLsizei count, const GLuint *value);
extern void glUniform3uiv (GLint location, GLsizei count, const GLuint *value);
extern void glUniform4uiv (GLint location, GLsizei count, const GLuint *value);
extern void glTexParameterIiv (GLenum target, GLenum pname, const GLint *params);
extern void glTexParameterIuiv (GLenum target, GLenum pname, const GLuint *params);
extern void glGetTexParameterIiv (GLenum target, GLenum pname, GLint *params);
extern void glGetTexParameterIuiv (GLenum target, GLenum pname, GLuint *params);
extern void glClearBufferiv (GLenum buffer, GLint drawbuffer, const GLint *value);
extern void glClearBufferuiv (GLenum buffer, GLint drawbuffer, const GLuint *value);
extern void glClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat *value);
extern void glClearBufferfi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
extern const_GLubyte_* glGetStringi (GLenum name, GLuint index);
extern GLboolean glIsRenderbuffer (GLuint renderbuffer);
extern void glBindRenderbuffer (GLenum target, GLuint renderbuffer);
extern void glDeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers);
extern void glGenRenderbuffers (GLsizei n, GLuint *renderbuffers);
extern void glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern void glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params);
extern GLboolean glIsFramebuffer (GLuint framebuffer);
extern void glBindFramebuffer (GLenum target, GLuint framebuffer);
extern void glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers);
extern void glGenFramebuffers (GLsizei n, GLuint *framebuffers);
extern GLenum glCheckFramebufferStatus (GLenum target);
extern void glFramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void glFramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
extern void glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params);
extern void glGenerateMipmap (GLenum target);
extern void glBlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
extern void glRenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
extern void glFramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
extern void* glMapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
extern void glFlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length);
extern void glBindVertexArray (GLuint array);
extern void glDeleteVertexArrays (GLsizei n, const GLuint *arrays);
extern void glGenVertexArrays (GLsizei n, GLuint *arrays);
extern GLboolean glIsVertexArray (GLuint array);
extern void glDrawArraysInstanced (GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
extern void glDrawElementsInstanced (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
extern void glTexBuffer (GLenum target, GLenum internalformat, GLuint buffer);
extern void glPrimitiveRestartIndex (GLuint index);
extern void glCopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
extern void glGetUniformIndices (GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices);
extern void glGetActiveUniformsiv (GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
extern void glGetActiveUniformName (GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName);
extern GLuint glGetUniformBlockIndex (GLuint program, const GLchar *uniformBlockName);
extern void glGetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
extern void glGetActiveUniformBlockName (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
extern void glUniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
extern void glDrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
extern void glDrawRangeElementsBaseVertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
extern void glDrawElementsInstancedBaseVertex (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
extern void glMultiDrawElementsBaseVertex (GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount, const GLint *basevertex);
extern void glProvokingVertex (GLenum mode);
extern GLsync glFenceSync (GLenum condition, GLbitfield flags);
extern GLboolean glIsSync (GLsync sync);
extern void glDeleteSync (GLsync sync);
extern GLenum glClientWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout);
extern void glWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout);
extern void glGetInteger64v (GLenum pname, GLint64 *data);
extern void glGetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
extern void glGetInteger64i_v (GLenum target, GLuint index, GLint64 *data);
extern void glGetBufferParameteri64v (GLenum target, GLenum pname, GLint64 *params);
extern void glFramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level);
extern void glTexImage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
extern void glTexImage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
extern void glGetMultisamplefv (GLenum pname, GLuint index, GLfloat *val);
extern void glSampleMaski (GLuint maskNumber, GLbitfield mask);
extern void glBindFragDataLocationIndexed (GLuint program, GLuint colorNumber, GLuint index, const GLchar *name);
extern GLint glGetFragDataIndex (GLuint program, const GLchar *name);
extern void glGenSamplers (GLsizei count, GLuint *samplers);
extern void glDeleteSamplers (GLsizei count, const GLuint *samplers);
extern GLboolean glIsSampler (GLuint sampler);
extern void glBindSampler (GLuint unit, GLuint sampler);
extern void glSamplerParameteri (GLuint sampler, GLenum pname, GLint param);
extern void glSamplerParameteriv (GLuint sampler, GLenum pname, const GLint *param);
extern void glSamplerParameterf (GLuint sampler, GLenum pname, GLfloat param);
extern void glSamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat *param);
extern void glSamplerParameterIiv (GLuint sampler, GLenum pname, const GLint *param);
extern void glSamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint *param);
extern void glGetSamplerParameteriv (GLuint sampler, GLenum pname, GLint *params);
extern void glGetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint *params);
extern void glGetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat *params);
extern void glGetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint *params);
extern void glQueryCounter (GLuint id, GLenum target);
extern void glGetQueryObjecti64v (GLuint id, GLenum pname, GLint64 *params);
extern void glGetQueryObjectui64v (GLuint id, GLenum pname, GLuint64 *params);
extern void glVertexAttribDivisor (GLuint index, GLuint divisor);
extern void glVertexAttribP1ui (GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void glVertexAttribP1uiv (GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
extern void glVertexAttribP2ui (GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void glVertexAttribP2uiv (GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
extern void glVertexAttribP3ui (GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void glVertexAttribP3uiv (GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
extern void glVertexAttribP4ui (GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void glVertexAttribP4uiv (GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
extern void glMinSampleShading (GLfloat value);
extern void glBlendEquationi (GLuint buf, GLenum mode);
extern void glBlendEquationSeparatei (GLuint buf, GLenum modeRGB, GLenum modeAlpha);
extern void glBlendFunci (GLuint buf, GLenum src, GLenum dst);
extern void glBlendFuncSeparatei (GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
extern void glDrawArraysIndirect (GLenum mode, const void *indirect);
extern void glDrawElementsIndirect (GLenum mode, GLenum type, const void *indirect);
extern void glUniform1d (GLint location, GLdouble x);
extern void glUniform2d (GLint location, GLdouble x, GLdouble y);
extern void glUniform3d (GLint location, GLdouble x, GLdouble y, GLdouble z);
extern void glUniform4d (GLint location, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void glUniform1dv (GLint location, GLsizei count, const GLdouble *value);
extern void glUniform2dv (GLint location, GLsizei count, const GLdouble *value);
extern void glUniform3dv (GLint location, GLsizei count, const GLdouble *value);
extern void glUniform4dv (GLint location, GLsizei count, const GLdouble *value);
extern void glUniformMatrix2dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix3dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix4dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix2x3dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix2x4dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix3x2dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix3x4dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix4x2dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glUniformMatrix4x3dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glGetUniformdv (GLuint program, GLint location, GLdouble *params);
extern GLint glGetSubroutineUniformLocation (GLuint program, GLenum shadertype, const GLchar *name);
extern GLuint glGetSubroutineIndex (GLuint program, GLenum shadertype, const GLchar *name);
extern void glGetActiveSubroutineUniformiv (GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint *values);
extern void glGetActiveSubroutineUniformName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name);
extern void glGetActiveSubroutineName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name);
extern void glUniformSubroutinesuiv (GLenum shadertype, GLsizei count, const GLuint *indices);
extern void glGetUniformSubroutineuiv (GLenum shadertype, GLint location, GLuint *params);
extern void glGetProgramStageiv (GLuint program, GLenum shadertype, GLenum pname, GLint *values);
extern void glPatchParameteri (GLenum pname, GLint value);
extern void glPatchParameterfv (GLenum pname, const GLfloat *values);
extern void glBindTransformFeedback (GLenum target, GLuint id);
extern void glDeleteTransformFeedbacks (GLsizei n, const GLuint *ids);
extern void glGenTransformFeedbacks (GLsizei n, GLuint *ids);
extern GLboolean glIsTransformFeedback (GLuint id);
extern void glPauseTransformFeedback (void);
extern void glResumeTransformFeedback (void);
extern void glDrawTransformFeedback (GLenum mode, GLuint id);
extern void glDrawTransformFeedbackStream (GLenum mode, GLuint id, GLuint stream);
extern void glBeginQueryIndexed (GLenum target, GLuint index, GLuint id);
extern void glEndQueryIndexed (GLenum target, GLuint index);
extern void glGetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint *params);
extern void glReleaseShaderCompiler (void);
extern void glShaderBinary (GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length);
extern void glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
extern void glDepthRangef (GLfloat n, GLfloat f);
extern void glClearDepthf (GLfloat d);
extern void glGetProgramBinary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
extern void glProgramBinary (GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
extern void glProgramParameteri (GLuint program, GLenum pname, GLint value);
extern void glUseProgramStages (GLuint pipeline, GLbitfield stages, GLuint program);
extern void glActiveShaderProgram (GLuint pipeline, GLuint program);
extern GLuint glCreateShaderProgramv (GLenum type, GLsizei count, const GLchar *const*strings);
extern void glBindProgramPipeline (GLuint pipeline);
extern void glDeleteProgramPipelines (GLsizei n, const GLuint *pipelines);
extern void glGenProgramPipelines (GLsizei n, GLuint *pipelines);
extern GLboolean glIsProgramPipeline (GLuint pipeline);
extern void glGetProgramPipelineiv (GLuint pipeline, GLenum pname, GLint *params);
extern void glProgramUniform1i (GLuint program, GLint location, GLint v0);
extern void glProgramUniform1iv (GLuint program, GLint location, GLsizei count, const GLint *value);
extern void glProgramUniform1f (GLuint program, GLint location, GLfloat v0);
extern void glProgramUniform1fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void glProgramUniform1d (GLuint program, GLint location, GLdouble v0);
extern void glProgramUniform1dv (GLuint program, GLint location, GLsizei count, const GLdouble *value);
extern void glProgramUniform1ui (GLuint program, GLint location, GLuint v0);
extern void glProgramUniform1uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void glProgramUniform2i (GLuint program, GLint location, GLint v0, GLint v1);
extern void glProgramUniform2iv (GLuint program, GLint location, GLsizei count, const GLint *value);
extern void glProgramUniform2f (GLuint program, GLint location, GLfloat v0, GLfloat v1);
extern void glProgramUniform2fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void glProgramUniform2d (GLuint program, GLint location, GLdouble v0, GLdouble v1);
extern void glProgramUniform2dv (GLuint program, GLint location, GLsizei count, const GLdouble *value);
extern void glProgramUniform2ui (GLuint program, GLint location, GLuint v0, GLuint v1);
extern void glProgramUniform2uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void glProgramUniform3i (GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
extern void glProgramUniform3iv (GLuint program, GLint location, GLsizei count, const GLint *value);
extern void glProgramUniform3f (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void glProgramUniform3fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void glProgramUniform3d (GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2);
extern void glProgramUniform3dv (GLuint program, GLint location, GLsizei count, const GLdouble *value);
extern void glProgramUniform3ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
extern void glProgramUniform3uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void glProgramUniform4i (GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void glProgramUniform4iv (GLuint program, GLint location, GLsizei count, const GLint *value);
extern void glProgramUniform4f (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void glProgramUniform4fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void glProgramUniform4d (GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
extern void glProgramUniform4dv (GLuint program, GLint location, GLsizei count, const GLdouble *value);
extern void glProgramUniform4ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern void glProgramUniform4uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void glProgramUniformMatrix2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix2dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix3dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix4dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix2x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix3x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix2x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix4x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix3x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix4x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void glProgramUniformMatrix2x3dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix3x2dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix2x4dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix4x2dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix3x4dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glProgramUniformMatrix4x3dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
extern void glValidateProgramPipeline (GLuint pipeline);
extern void glGetProgramPipelineInfoLog (GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
extern void glVertexAttribL1d (GLuint index, GLdouble x);
extern void glVertexAttribL2d (GLuint index, GLdouble x, GLdouble y);
extern void glVertexAttribL3d (GLuint index, GLdouble x, GLdouble y, GLdouble z);
extern void glVertexAttribL4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void glVertexAttribL1dv (GLuint index, const GLdouble *v);
extern void glVertexAttribL2dv (GLuint index, const GLdouble *v);
extern void glVertexAttribL3dv (GLuint index, const GLdouble *v);
extern void glVertexAttribL4dv (GLuint index, const GLdouble *v);
extern void glVertexAttribLPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
extern void glGetVertexAttribLdv (GLuint index, GLenum pname, GLdouble *params);
extern void glViewportArrayv (GLuint first, GLsizei count, const GLfloat *v);
extern void glViewportIndexedf (GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
extern void glViewportIndexedfv (GLuint index, const GLfloat *v);
extern void glScissorArrayv (GLuint first, GLsizei count, const GLint *v);
extern void glScissorIndexed (GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height);
extern void glScissorIndexedv (GLuint index, const GLint *v);
extern void glDepthRangeArrayv (GLuint first, GLsizei count, const GLdouble *v);
extern void glDepthRangeIndexed (GLuint index, GLdouble n, GLdouble f);
extern void glGetFloati_v (GLenum target, GLuint index, GLfloat *data);
extern void glGetDoublei_v (GLenum target, GLuint index, GLdouble *data);
extern void glDrawArraysInstancedBaseInstance (GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
extern void glDrawElementsInstancedBaseInstance (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLuint baseinstance);
extern void glDrawElementsInstancedBaseVertexBaseInstance (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
extern void glGetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params);
extern void glGetActiveAtomicCounterBufferiv (GLuint program, GLuint bufferIndex, GLenum pname, GLint *params);
extern void glBindImageTexture (GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
extern void glMemoryBarrier (GLbitfield barriers);
extern void glTexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
extern void glTexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern void glTexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
extern void glDrawTransformFeedbackInstanced (GLenum mode, GLuint id, GLsizei instancecount);
extern void glDrawTransformFeedbackStreamInstanced (GLenum mode, GLuint id, GLuint stream, GLsizei instancecount);
extern void glClearBufferData (GLenum target, GLenum internalformat, GLenum format, GLenum type, const void *data);
extern void glClearBufferSubData (GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
extern void glDispatchCompute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
extern void glDispatchComputeIndirect (GLintptr indirect);
extern void glCopyImageSubData (GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
extern void glFramebufferParameteri (GLenum target, GLenum pname, GLint param);
extern void glGetFramebufferParameteriv (GLenum target, GLenum pname, GLint *params);
extern void glGetInternalformati64v (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 *params);
extern void glInvalidateTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth);
extern void glInvalidateTexImage (GLuint texture, GLint level);
extern void glInvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length);
extern void glInvalidateBufferData (GLuint buffer);
extern void glInvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments);
extern void glInvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glMultiDrawArraysIndirect (GLenum mode, const void *indirect, GLsizei drawcount, GLsizei stride);
extern void glMultiDrawElementsIndirect (GLenum mode, GLenum type, const void *indirect, GLsizei drawcount, GLsizei stride);
extern void glGetProgramInterfaceiv (GLuint program, GLenum programInterface, GLenum pname, GLint *params);
extern GLuint glGetProgramResourceIndex (GLuint program, GLenum programInterface, const GLchar *name);
extern void glGetProgramResourceName (GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
extern void glGetProgramResourceiv (GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
extern GLint glGetProgramResourceLocation (GLuint program, GLenum programInterface, const GLchar *name);
extern GLint glGetProgramResourceLocationIndex (GLuint program, GLenum programInterface, const GLchar *name);
extern void glShaderStorageBlockBinding (GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
extern void glTexBufferRange (GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern void glTexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
extern void glTexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
extern void glTextureView (GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers);
extern void glBindVertexBuffer (GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
extern void glVertexAttribFormat (GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
extern void glVertexAttribIFormat (GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern void glVertexAttribLFormat (GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern void glVertexAttribBinding (GLuint attribindex, GLuint bindingindex);
extern void glVertexBindingDivisor (GLuint bindingindex, GLuint divisor);
extern void glDebugMessageControl (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
extern void glDebugMessageInsert (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
extern void glDebugMessageCallback (GLDEBUGPROC callback, const void *userParam);
extern GLuint glGetDebugMessageLog (GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog);
extern void glPushDebugGroup (GLenum source, GLuint id, GLsizei length, const GLchar *message);
extern void glPopDebugGroup (void);
extern void glObjectLabel (GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
extern void glGetObjectLabel (GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
extern void glObjectPtrLabel (const void *ptr, GLsizei length, const GLchar *label);
extern void glGetObjectPtrLabel (const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);
extern void glBufferStorage (GLenum target, GLsizeiptr size, const void *data, GLbitfield flags);
extern void glClearTexImage (GLuint texture, GLint level, GLenum format, GLenum type, const void *data);
extern void glClearTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data);
extern void glBindBuffersBase (GLenum target, GLuint first, GLsizei count, const GLuint *buffers);
extern void glBindBuffersRange (GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes);
extern void glBindTextures (GLuint first, GLsizei count, const GLuint *textures);
extern void glBindSamplers (GLuint first, GLsizei count, const GLuint *samplers);
extern void glBindImageTextures (GLuint first, GLsizei count, const GLuint *textures);
extern void glBindVertexBuffers (GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
extern GLuint64 glGetTextureHandleARB (GLuint texture);
extern GLuint64 glGetTextureSamplerHandleARB (GLuint texture, GLuint sampler);
extern void glMakeTextureHandleResidentARB (GLuint64 handle);
extern void glMakeTextureHandleNonResidentARB (GLuint64 handle);
extern GLuint64 glGetImageHandleARB (GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum format);
extern void glMakeImageHandleResidentARB (GLuint64 handle, GLenum access);
extern void glMakeImageHandleNonResidentARB (GLuint64 handle);
extern void glUniformHandleui64ARB (GLint location, GLuint64 value);
extern void glUniformHandleui64vARB (GLint location, GLsizei count, const GLuint64 *value);
extern void glProgramUniformHandleui64ARB (GLuint program, GLint location, GLuint64 value);
extern void glProgramUniformHandleui64vARB (GLuint program, GLint location, GLsizei count, const GLuint64 *values);
extern GLboolean glIsTextureHandleResidentARB (GLuint64 handle);
extern GLboolean glIsImageHandleResidentARB (GLuint64 handle);
extern void glVertexAttribL1ui64ARB (GLuint index, GLuint64EXT x);
extern void glVertexAttribL1ui64vARB (GLuint index, const GLuint64EXT *v);
extern void glGetVertexAttribLui64vARB (GLuint index, GLenum pname, GLuint64EXT *params);
extern GLsync glCreateSyncFromCLeventARB (struct _cl_context *context, struct _cl_event *event, GLbitfield flags);
extern void glDispatchComputeGroupSizeARB (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z, GLuint group_size_x, GLuint group_size_y, GLuint group_size_z);
extern void glDebugMessageControlARB (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
extern void glDebugMessageInsertARB (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
extern void glDebugMessageCallbackARB (GLDEBUGPROCARB callback, const void *userParam);
extern GLuint glGetDebugMessageLogARB (GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog);
extern void glBlendEquationiARB (GLuint buf, GLenum mode);
extern void glBlendEquationSeparateiARB (GLuint buf, GLenum modeRGB, GLenum modeAlpha);
extern void glBlendFunciARB (GLuint buf, GLenum src, GLenum dst);
extern void glBlendFuncSeparateiARB (GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
extern void glMultiDrawArraysIndirectCountARB (GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
extern void glMultiDrawElementsIndirectCountARB (GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
extern GLenum glGetGraphicsResetStatusARB (void);
extern void glGetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *img);
extern void glReadnPixelsARB (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
extern void glGetnCompressedTexImageARB (GLenum target, GLint lod, GLsizei bufSize, void *img);
extern void glGetnUniformfvARB (GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
extern void glGetnUniformivARB (GLuint program, GLint location, GLsizei bufSize, GLint *params);
extern void glGetnUniformuivARB (GLuint program, GLint location, GLsizei bufSize, GLuint *params);
extern void glGetnUniformdvARB (GLuint program, GLint location, GLsizei bufSize, GLdouble *params);
extern void glMinSampleShadingARB (GLfloat value);
extern void glNamedStringARB (GLenum type, GLint namelen, const GLchar *name, GLint stringlen, const GLchar *string);
extern void glDeleteNamedStringARB (GLint namelen, const GLchar *name);
extern void glCompileShaderIncludeARB (GLuint shader, GLsizei count, const GLchar *const*path, const GLint *length);
extern GLboolean glIsNamedStringARB (GLint namelen, const GLchar *name);
extern void glGetNamedStringARB (GLint namelen, const GLchar *name, GLsizei bufSize, GLint *stringlen, GLchar *string);
extern void glGetNamedStringivARB (GLint namelen, const GLchar *name, GLenum pname, GLint *params);
extern void glTexPageCommitmentARB (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLboolean resident);
